### ISSUE TITLE
Daroou2, noopkat, skoufcodes

### ISSUE THREAD

**Issue by danellis** [TwitchCoders/twitchcoders.github.io#4]
https://www.twitch.tv/daroou2 generally on Monday and Wednesday nights at 9 pm EST
https://www.twitch.tv/noopkat  Sundays, approximately 11am EST
https://www.twitch.tv/skoufcodes 9am AEST on Saturday and Sunday mornings; 8pm AEST some weekdays

**Comment by eddiejaoude** [comment]
Thank you! 👍 

Added to the main list in the README 🤓
