### ISSUE TITLE
add a column with programming language(s)

### ISSUE THREAD

**Issue by Evelinabrink** [TwitchCoders/twitchcoders.github.io#7]

**Comment by eddiejaoude** [comment]
Good idea, done...

<img width="939" alt="screenshot 2018-05-19 16 32 22" src="https://user-images.githubusercontent.com/624760/40270296-41955f20-5b82-11e8-89f4-0d56ce375acc.png">

What do you think?

**Comment by Evelinabrink** [comment]
looks good!

**Comment by eddiejaoude** [comment]
Ok great, I will close this issue. Any more ideas please log a new issue 🤓
